### ISSUE TITLE
Improve Assembly Organization

### ISSUE THREAD

**Issue by Michael-DST** [PrismLibrary/Prism.Wpf#1]
Reference: http://compositewpf.codeplex.com/discussions/581235

**Comment by brianlagunas** [comment]
Modularity is the concept dynamically discovering and loading assemblies at runtime.  Mobile and tablet does not support this.  Composition is the concept of injecting views into regions of a view, which does not make sense on mobile.  Mobile has its own navigation mechanism, which greatly differs depending on platform (iOS, Android, Phone, etc).  So there will not be any code sharing there.  Xamarin.Forms abtracts these different navigation patterns sot hat Prism can target Forms instead.  Even then, there are some challenges since navigation on the mobile platforms is tightly coupled to the views.

It is really at the point where Prism for Desktop will be complete different guidance than Prism for mobile.  We see this already for Prism for WInRT.  The only code that can be shared across all XAML platforms is Prism.Mvvm and Prism.PubSubEvents.

The naming of Prism.Mvvm is because all of the classes (base classes, commanding, ViewModelLocator, etc.) within it support the MVVM pattern.  So in this case it makes perfect sense to include MVVM in the assembly name.  The reason for Prism.SharedInterfaces exists is because Prism.Mvvm and Prism.Composition require it.  If we placed IActiveAware in Prism.Mvvm then we are forcing Prism.Composition to take that dependency.  Though, I will say that I can't imagine having a Prism app that doesn't use DelegateCommand, but the way it is now, it isn't being forced on anyone.  Also, not every platform will take advantage of IActiveAware.  If anything, maybe VML gets pulled out into it's own assembly, while all the base commanding stuff (including IActiveAware) become core to Prism.

When you start trying to shared code for application architecture guidance across multiple platforms, you realize that every platform will have completely different guidance.  So we share where we can, and then implement the specific guidance for each platform.

We also have to be careful on how much assembly changing we do.  We don't want to piss everyone off by breaking their apps.  That might lead to loss of adoption.

Lot's to think about.

**Comment by Michael-DST** [comment]
Yes agreed.  I do not have enough experience w/ mobile to agree/argue with your comments.  It just seems to me that modularity/composition can still work in these environments, but you do bring up good points.

As far as breaking changes go... that's the point of versioning, anyways.  I think the EF team has the right approach to this.  Take 4.x to 5.0, for instance... I am essentially assuming/expecting things to change between versions when I upgrade.  That's me, however.  Others might not have this expectation, which is where good communication comes in, ala EF7 team. :)

**Comment by Michael-DST** [comment]
Also, another thing to consider, is that XF has its own presentation model.  They basically brought all the magic of WPF and PCL'd it.  There are BindingProperties that can be instance-based or attached.  It's pretty amazing.  I can't wait to dig into it to see how to use it, but it's just a thought going forward.  It's a whole new paradigm... I for one feel alive as a coder again!  It's like 2011, before the disaster that was Mix'11, that is. :P

**Comment by brianlagunas** [comment]
Yes, Xamarin.Forms is very similar in terms of XAML, but also very different.

**Comment by brianlagunas** [comment]
How would you feel if we renamed all the assemblies and CLR/XAML namespaces to remove the "Microsoft.Practices" prefixes, and reorganized the solution to remove dependencies and better align with cross-platform support?  Keep in mind, this would completely break your current Prism applications.  Upgrading wouldn't be too painful though, as a Find and Replace should fix most of it.  Nuget would take care of the assembly references, unless you manually added the references.

**Comment by Michael-DST** [comment]
Are you suggesting it would be named "Prism.*" ?  I am partial to the longer namespaces, but I know a lot of people aren't.  I am ambivalent really either way.  What makes more sense to me is to make sure the core intent of the assemblies are named in a satisfying way. :)

As for Xaml namespaces... making use of the XmlnsPrefix and XmlnsDefinition attributes go a long way to help with this sort of thing, but I use ReSharper, so it's no big deal to me.  Again, just make sure you communicate this clearly and it shouldn't be a problem.  This is just my opinion, however, and I am sure you will get more feedback if you ask more people (such is the plight of software, or humans, really. :P )

Speaking of breaking changes... ASPNET5 was "announced" today (or I should say, "officially" announced) on ScottGu's blog, and it has basically been completely overhauled from top to bottom.  Same thing there.  If I am using a whole new version, I don't expect it to "just work" cleanly... there will be some adjustments to be made....  but again, just me. :)

**Comment by brianlagunas** [comment]
Prism has been restructured.

**Comment by Michael-DST** [comment]
Awesome!  Thank you!

**Comment by Michael-DST** [comment]
I just (finally) had the chance to fork and review the current solution (under the "Prism" project)... looks really really good!  Great work. :+1:
